language: php

dist: trusty

env:
  global:
    - TRAVIS_NODE_VERSION="10"

matrix:
  include:
    - php: '7.1'
      env: DB=MYSQL CORE_RELEASE=3.7 PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: '7.1'
      env: DB=MYSQL CORE_RELEASE=3.7 NPM_TEST=1
    - php: '7.2'
      env: DB=MYSQL CORE_RELEASE=3.7 PHPUNIT_TEST=1
    - php: '7.3'
      env: DB=MYSQL CORE_RELEASE=3.7 PHPUNIT_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

  # Install NPM dependencies
  - if [[ $NPM_TEST ]]; then (cd security-extensions && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && yarn run build); fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit security-extensions/tests; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=security-extensions/phpcs.xml.dist security-extensions/src security-extensions/tests; fi
  - if [[ $NPM_TEST ]]; then (cd security-extensions && git diff-files --quiet -w --relative=client); fi
  - if [[ $NPM_TEST ]]; then (cd security-extensions && git diff --name-status --relative=client); fi
  - if [[ $NPM_TEST ]]; then (cd security-extensions && yarn run lint); fi
