---
Name: securityextensionsservices
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SecurityExtensions\Service\SudoModeServiceInterface:
    class: SilverStripe\SecurityExtensions\Service\SudoModeService
